# Generated by Django 3.2.19 on 2023-07-11 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_alter_photo_description'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='to_photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='photos.photo'),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_photo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, to='photos.photo'),
        ),
    ]
