# Generated by Django 3.2.19 on 2023-07-14 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_time_of_publication']},
        ),
    ]
