# Generated by Django 3.2.19 on 2023-07-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_alter_pet_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='slug',
            new_name='pet_slug',
        ),
    ]
